version: '3.7'

services:
  wetrekking-prod:
    image: asia.gcr.io/wetrekking-376511/team-wetrekking-prod:2.0
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
