FROM node:14-alpine

COPY ./package.json /team-wetrekking/
WORKDIR /team-wetrekking/

RUN yarn install --production --network-timeout 1000000

COPY . /team-wetrekking/
RUN yarn build
CMD yarn start:prod